# Generated by Django 4.2.6 on 2023-10-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_todouserprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todouserprofile',
            old_name='account',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='todouserprofile',
            name='password1',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
